'use client';
import Link from 'next/link';
import { Bell, BookOpen, Bot, CalendarDays, ChartNoAxesCombined, ChevronRight, ClipboardCheck, FileText, FolderOpen, LayoutDashboard, LogOut, Menu, Settings, Sparkles, Target, UserRound, WandSparkles, X } from 'lucide-react';
import { usePathname } from 'next/navigation';
import { useState } from 'react';

const primary = [
  ['Dashboard','/dashboard',LayoutDashboard], ['My Learning','/learning',BookOpen], ['My Materials','/materials',FolderOpen], ['AI Assistant','/assistant',Bot], ['Tasks & Assignments','/tasks',ClipboardCheck], ['Study Planner','/planner',CalendarDays], ['Exams & Readiness','/exams',Target], ['Quizzes','/quizzes',FileText]
] as const;
const secondary = [['Analytics','/analytics',ChartNoAxesCombined],['What-If Simulator','/simulator',WandSparkles],['Learning Profile','/profile',UserRound],['Notifications','/notifications',Bell],['Settings','/settings',Settings]] as const;
export function AppShell({ children }: { children: React.ReactNode }) {
 const path = usePathname(); const [open,setOpen] = useState(false);
 const links = (items: typeof primary | typeof secondary) => items.map(([label,href,Icon]) => <Link onClick={()=>setOpen(false)} href={href} key={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${path===href?'bg-primary text-white shadow-lg shadow-primary/20':'text-muted hover:bg-highlight/40 hover:text-deep'}`}><Icon size={18}/><span>{label}</span></Link>);
 return <div className="min-h-screen bg-canvas"><button aria-label="Open navigation" onClick={()=>setOpen(true)} className="fixed left-4 top-4 z-40 rounded-xl bg-white p-2 text-primary shadow-soft lg:hidden"><Menu/></button><aside className={`fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-highlight/40 bg-white p-6 transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="mb-9 flex items-center justify-between"><Link href="/dashboard" className="flex items-center gap-2 text-2xl font-black tracking-tight text-ink"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary text-white"><Sparkles size={19}/></span>Luna<span className="text-primary">Learn</span></Link><button className="lg:hidden" onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button></div><div className="mb-5 rounded-3xl bg-gradient-to-br from-highlight/60 to-white p-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-deep text-sm font-bold text-white">AV</div><div><p className="font-bold">Aarav Verma</p><p className="text-xs text-muted">B.Tech · Semester 4</p></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white"><div className="h-full w-3/4 rounded-full bg-primary"/></div><p className="mt-2 text-xs font-medium text-deep">Level 8 · 2,480 XP</p></div><nav className="scrollbar-none flex-1 space-y-1 overflow-y-auto">{links(primary)}<p className="mb-2 mt-6 px-3 text-[10px] font-bold uppercase tracking-[.16em] text-muted">Explore</p>{links(secondary)}</nav><Link href="/login" className="mt-6 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-muted hover:bg-highlight/40"><LogOut size={18}/>Sign out</Link></aside><main className="min-h-screen lg:ml-72"><header className="sticky top-0 z-30 flex h-20 items-center justify-end gap-3 border-b border-highlight/30 bg-canvas/85 px-5 backdrop-blur-xl sm:px-8"><div className="mr-auto hidden text-sm text-muted md:block">Tuesday, 21 September</div><Link href="/notifications" className="relative grid h-10 w-10 place-items-center rounded-xl bg-white text-muted shadow-sm"><Bell size={18}/><i className="absolute right-2 top-2 h-2 w-2 rounded-full bg-primary"/></Link><button className="flex items-center gap-2 rounded-xl bg-white px-2 py-1.5 text-sm font-semibold shadow-sm">AV <ChevronRight size={15}/></button></header><div className="mx-auto max-w-[1600px] p-5 sm:p-8">{children}</div></main></div>
}
