"use client";
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useAcademic } from '@/lib/context/AcademicContext';
import { api } from '@/lib/api';
import { examCountdown } from '@/lib/dates';
import { AcademicDataErrorBanner, AcademicDataSkeleton, Card, PageHeader, Progress, Risk } from './Ui';
import { ReadinessDetails } from './ReadinessDetails';

export function Dashboard() {
 const {profile,subjects,tasks,exams,readinessMap,risks,plannerContext,asyncState,refreshAll}=useAcademic();
 const [activity,setActivity]=useState<Awaited<ReturnType<typeof api.activity.get>>|null>(null),[activityError,setActivityError]=useState(''),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(false);
 const timezone=profile?.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone;
 const dayKey=(date:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
 const today=dayKey(new Date());
 const [month,setMonth]=useState(()=>new Date(today+'T12:00:00')),[selected,setSelected]=useState(today);
 useEffect(()=>{let active=true;api.activity.get().then(d=>{if(active){setActivity(d);setActivityError('');}}).catch(e=>{if(active)setActivityError(e.message);});return()=>{active=false;};},[plannerContext?.generated_at]);
 if(asyncState.status==='idle'||asyncState.status==='loading'||asyncState.status==='retrying')return <AcademicDataSkeleton label="Loading dashboard"/>;
 if(asyncState.status==='error')return <AcademicDataErrorBanner message={asyncState.error?.userMessage || 'Could not load academic data'} onRetry={()=>void refreshAll()}/>;
 const upcoming=exams.filter(e=>Date.parse(e.exam_date)>=Date.now()).sort((a,b)=>Date.parse(a.exam_date)-Date.parse(b.exam_date));
 const next=upcoming[0],readiness=next?readinessMap[next.subject_id]:undefined;
 const plan=plannerContext?.study_plan;
 const block=plan?.blocks.find(b=>Date.parse(b.end)>Date.now());
 const pending=tasks.filter(t=>!t.is_completed).sort((a,b)=>(a.due_date?Date.parse(a.due_date):Infinity)-(b.due_date?Date.parse(b.due_date):Infinity));
 const logged=activity?.sessions.filter(s=>dayKey(new Date(s.started_at))===today).reduce((n,s)=>n+s.duration_minutes,0);
 type Event={id:string;date:string;label:string;kind:string;href:string;taskId?:string};
 const events:Event[]=[...exams.map(e=>({id:e.id,date:e.exam_date,label:e.title,kind:'Exam',href:`/exams?subject=${e.subject_id}#${e.id}`})),...tasks.filter(t=>t.due_date).map(t=>({id:t.id,date:t.due_date!,label:t.title,kind:t.is_completed?'Completed task':'Task deadline',href:`/tasks#${t.id}`,taskId:t.is_completed?undefined:t.id})),...(activity?.sessions || []).map(s=>({id:s.id,date:s.started_at,label:`${s.duration_minutes} min ${s.session_type}`,kind:'Logged session',href:'/planner#study-activity'})),...(plan?.blocks || []).map(b=>({id:b.id,date:b.start,label:b.title,kind:`Planned · ${b.minutes} min`,href:'/planner'}))];
 const selectedEvents=events.filter(e=>dayKey(new Date(e.date))===selected).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date));
 const y=month.getFullYear(),m=month.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();
 const monthKey=(day:number)=>`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
 async function complete(id:string){setBusy(true);setActionError('');try{const task=tasks.find(t=>t.id===id);await api.tasks.update(id,{is_completed:true},task?.updated_at);await refreshAll();}catch(e){setActionError(e instanceof Error?e.message:'Could not complete task');}finally{setBusy(false);}}
 return <div className="space-y-5">
  <PageHeader title={`Good day, ${profile?.full_name?.split(' ')[0] || 'student'}`} description="Your next study action, deadlines and progress in one place." action={<Link href="/learning" className="rounded-xl bg-primary px-4 py-3 text-sm font-bold text-white">Manage subjects</Link>}/>
  {subjects.length===0 && <Card><h2 className="text-xl font-bold">Build your academic workspace</h2><p className="my-2 text-muted">Add a subject and its topics to start. Your calendar can also track general tasks.</p><Link href="/learning" className="text-primary">Add your first subject →</Link></Card>}
  <div className="grid gap-4 md:grid-cols-3"><Card><p className="text-xs text-muted">Nearest upcoming exam</p><h2 className="mt-2 text-lg font-bold">{next?.title || 'No upcoming exam'}</h2><p className="mt-1 text-sm text-primary">{next?examCountdown(next.exam_date):'Add an exam to plan preparation'}</p></Card><Card><p className="text-xs text-muted">Readiness for nearest exam</p><p className="my-2 text-3xl font-black text-primary">{readiness?`${readiness.readiness_percentage}%`:'Not available'}</p>{readiness && <ReadinessDetails readiness={readiness}/>}</Card><Card><p className="text-xs text-muted">Today’s logged study / daily availability</p><p className="my-2 text-2xl font-bold">{logged===undefined?'—':`${logged} min`} / {Math.round((plannerContext?.student.study_time_settings.available_hours_per_day ?? 2)*60)} min</p><Link className="text-sm text-primary" href="/planner#study-activity">Log completed study</Link>{activityError && <p role="alert" className="text-xs text-red-600">{activityError}</p>}</Card></div>
  <div className="grid gap-5 xl:grid-cols-[1.3fr_1fr]"><div className="space-y-5"><Card className="bg-gradient-to-br from-primary/10 to-highlight/20"><p className="text-xs font-bold uppercase tracking-wider text-primary">Next study action</p><h2 className="my-3 text-2xl font-bold">{block?.title || 'Build your next study plan'}</h2><p className="text-sm text-muted">{block?`${block.minutes} minutes · ${block.reason}`:plan?.issues[0] || 'Set remaining work estimates and availability to schedule useful study blocks.'}</p><Link href="/planner" className="mt-4 inline-block rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white">Open study planner</Link></Card><Card><div className="flex justify-between"><h2 className="font-bold">Priority tasks</h2><Link className="text-sm text-primary" href="/tasks">View all</Link></div>{pending.length===0?<p className="mt-4 text-sm text-muted">No pending tasks.</p>:pending.slice(0,5).map(t=><div className="mt-3 flex items-center justify-between gap-3 border-t border-highlight/30 pt-3" key={t.id}><div><Link href={`/tasks#${t.id}`} className="font-semibold">{t.title}</Link><p className="text-xs text-muted">{t.priority} · {t.due_date?`${Date.parse(t.due_date)<Date.now()?'Overdue · ':''}${new Date(t.due_date).toLocaleString()}`:'No deadline'}</p></div><button disabled={busy} className="text-sm text-primary" onClick={()=>void complete(t.id)}>Complete</button></div>)}{actionError && <p role="alert" className="text-red-600">{actionError}</p>}</Card></div>
  <Card><div className="flex items-center justify-between gap-2"><button aria-label="Previous month" onClick={()=>setMonth(new Date(y,m-1,1))}>←</button><h2 className="font-bold">{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button aria-label="Next month" onClick={()=>setMonth(new Date(y,m+1,1))}>→</button><button className="text-sm text-primary" onClick={()=>{setMonth(new Date(today+'T12:00:00'));setSelected(today);}}>Today</button></div><p className="mt-1 text-xs text-muted">{timezone}</p><div className="mt-4 grid grid-cols-7 gap-1 text-center text-xs">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span className="p-2 text-muted" key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={`blank${i}`}/>)}{Array.from({length:days},(_,i)=>{const key=monthKey(i+1),count=events.filter(e=>dayKey(new Date(e.date))===key).length;return <button key={key} aria-label={`${key}, ${count} events`} aria-pressed={selected===key} onClick={()=>setSelected(key)} className={`min-h-10 rounded-lg p-2 ${selected===key?'bg-primary text-white':key===today?'border border-primary':'hover:bg-highlight/30'}`}>{i+1}<span className="block h-2">{count>0?'•':''}</span></button>;})}</div><h3 className="mt-5 font-bold">Agenda · {selected}</h3>{selectedEvents.length===0?<p className="mt-2 text-sm text-muted">No events on this date.</p>:<ul className="mt-2 space-y-3">{selectedEvents.map(e=><li key={`${e.kind}:${e.id}`} className="rounded-xl bg-canvas p-3"><span className="text-xs text-muted">{e.kind} · {new Date(e.date).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',timeZone:timezone})}</span><Link className="block text-sm font-bold text-primary" href={e.href}>{e.label}</Link>{e.taskId && <button disabled={busy} className="mt-1 text-xs underline" onClick={()=>void complete(e.taskId!)}>Mark complete</button>}</li>)}</ul>}</Card></div>
  <div className="grid gap-5 lg:grid-cols-2"><Card><h2 className="mb-3 font-bold">Subject progress</h2>{subjects.map(s=>{const r=readinessMap[s.id];return <div key={s.id} className="mb-4"><div className="mb-1 flex justify-between text-sm"><Link href={`/learning?subject=${s.id}`}>{s.name}</Link><span>{r?`${r.basis?.topics.completed ?? 0}/${r.basis?.topics.total ?? 0} topics · ${r.breakdown.topic_completion}%`:'Unavailable'}</span></div>{r && <Progress value={r.breakdown.topic_completion}/>}</div>})}</Card><Card><h2 className="mb-3 font-bold">What needs attention</h2>{risks.length===0?<p className="text-sm text-muted">No current risk alerts.</p>:<div className="space-y-3">{risks.slice(0,4).map((r,i)=><Risk key={i} label={r.type.replaceAll('_',' ')} detail={r.reason}/>)}</div>}</Card></div>
 </div>;
}
