'use client';
import { useState } from 'react';
import { api } from '@/lib/api';
import { useAcademic } from '@/lib/context/AcademicContext';
import { useTheme } from '@/lib/context/ThemeContext';
import { Card,PageHeader } from './Ui';
export function SettingsView(){
 const {profile,refreshAll,asyncState}=useAcademic();const {theme,setTheme}=useTheme();
 const [name,setName]=useState(profile?.full_name || ''),[course,setCourse]=useState(profile?.course || ''),[semester,setSemester]=useState(profile?.semester || 1),[hours,setHours]=useState(profile?.available_hours_per_day?.toString() ?? ''),[start,setStart]=useState(profile?.focus_start || '17:00'),[end,setEnd]=useState(profile?.focus_end || '19:00'),[timezone,setTimezone]=useState(profile?.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');setError('');try{await api.auth.updateSettings({full_name:name,course,semester,available_hours_per_day:hours===''?null:Number(hours),focus_start:start,focus_end:end,timezone});await refreshAll();setMessage('Settings saved and applied to your study plan.');}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setBusy(false);}}
 const input='block w-full rounded-xl border border-highlight bg-card p-2';
 return <><PageHeader title="Settings" description="Manage your profile, available study time and appearance."/><div className="grid gap-5 lg:grid-cols-2"><Card><form className="space-y-4 text-sm" onSubmit={save}><h2 className="font-bold">Profile and study preferences</h2><label className="block">Full name<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)} className={input}/></label><label className="block">Course<input required maxLength={120} value={course} onChange={e=>setCourse(e.target.value)} className={input}/></label><label className="block">Semester<input required type="number" min="1" max="12" value={semester} onChange={e=>setSemester(Number(e.target.value))} className={input}/></label><label className="block">Available hours per day<input type="number" min="0" max="24" step="0.25" value={hours} onChange={e=>setHours(e.target.value)} className={input}/><span className="text-xs text-muted">Blank uses the documented 2-hour default. Zero means no availability.</span></label><div className="grid grid-cols-2 gap-3"><label>Focus starts<input required type="time" value={start} onChange={e=>setStart(e.target.value)} className={input}/></label><label>Focus ends<input required type="time" value={end} onChange={e=>setEnd(e.target.value)} className={input}/></label></div><label className="block">Timezone<input required value={timezone} onChange={e=>setTimezone(e.target.value)} className={input}/></label><p className="text-xs text-muted">Use a same-day focus window. It limits where your available hours can be scheduled.</p>{error && <p role="alert" className="text-red-600">{error}</p>}{message && <p role="status" className="text-primary">{message}</p>}<button disabled={busy} className="rounded-xl bg-primary px-4 py-2 font-bold text-white">{busy?'Saving…':'Save settings'}</button></form></Card><div className="space-y-5"><Card><h2 className="font-bold">Appearance</h2><p className="mb-3 text-xs text-muted">Saved in this browser. System follows your OS appearance.</p><div className="flex gap-3">{(['light','dark','system'] as const).map(t=><button aria-pressed={theme===t} key={t} onClick={()=>setTheme(t)} className={`rounded-xl border p-3 ${theme===t?'border-primary bg-highlight/30':'border-highlight'}`}>{t}</button>)}</div></Card><Card><h2 className="font-bold">Data connection</h2><p className="mt-2 text-sm">{asyncState.status==='success'||asyncState.status==='empty'?'Academic records loaded successfully.':'Academic data is not currently synchronized.'}</p></Card></div></div></>;
}
