'use client';
import { useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { useAcademic } from '@/lib/context/AcademicContext';
import { Card, PageHeader } from './Ui';
export function SimulatorView(){
 const {subjects,plannerContext}=useAcademic();const [subject,setSubject]=useState(subjects[0]?.id || '');const [minutes,setMinutes]=useState(30);const [hours,setHours]=useState(plannerContext?.student.study_time_settings.available_hours_per_day ?? 2);const [completed,setCompleted]=useState<string[]>([]);const [result,setResult]=useState<Awaited<ReturnType<typeof api.planner.simulate>>|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const topics=plannerContext?.subjects.find(s=>s.subject_id===subject)?.weak_and_unfinished_topics || [];
 async function run(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{setResult(await api.planner.simulate({subject_id:subject,additional_minutes:minutes,completed_topic_ids:completed,available_hours_per_day:hours}));}catch(e){setError(e instanceof Error?e.message:'Scenario failed');}finally{setBusy(false);}}
 return <><PageHeader title="What-if simulator" description="Compare a hypothetical study choice with your real current readiness."/><div className="grid gap-5 lg:grid-cols-2"><Card><form onSubmit={run} className="space-y-4 text-sm"><label className="block">Subject<select required className="ml-3 rounded border bg-card p-2" value={subject} onChange={e=>{setSubject(e.target.value);setCompleted([]);setResult(null);}}><option value="">Choose subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="block">Additional study minutes<input required className="ml-3 w-24 rounded border bg-card p-2" type="number" min="0" max="1440" value={minutes} onChange={e=>{setMinutes(Number(e.target.value));setResult(null);}}/></label><label className="block">Daily availability (hours)<input required className="ml-3 w-24 rounded border bg-card p-2" type="number" min="0" max="24" step="0.25" value={hours} onChange={e=>{setHours(Number(e.target.value));setResult(null);}}/></label><fieldset><legend className="font-bold">Hypothetically complete topics</legend>{topics.filter(t=>t.status!=='completed').map(t=><label key={t.id} className="mt-2 block"><input type="checkbox" checked={completed.includes(t.id)} onChange={e=>{setCompleted(e.target.checked?[...completed,t.id]:completed.filter(id=>id!==t.id));setResult(null);}}/> {t.title}</label>)}</fieldset><button disabled={busy || !subject} className="rounded-xl bg-primary px-4 py-2 text-white">{busy?'Calculating…':'Calculate scenario'}</button>{error && <p role="alert" className="text-red-600">{error}</p>}</form></Card><Card>{result?<><h2 className="text-xl font-bold">{result.baseline}% → {result.projected}% ({result.delta>=0?'+':''}{result.delta} points)</h2><dl className="my-4 space-y-2 text-sm">{Object.entries(result.projected_breakdown).map(([key,value])=><div key={key} className="flex justify-between"><dt>{key.replaceAll('_',' ')}</dt><dd>{result.baseline_breakdown[key]}% → {value}%</dd></div>)}</dl><p>Required: {result.required_hours?.toFixed(1) ?? 'Unknown'}h · Available: {result.available_hours?.toFixed(1) ?? 'No upcoming exam'}{result.available_hours!==null?'h':''}</p><p className="my-3 text-sm">{result.reason}</p><ul className="list-disc pl-5 text-xs text-muted">{result.assumptions.map(a=><li key={a}>{a}</li>)}</ul><Link className="mt-4 block text-primary" href="/planner#study-activity">Log actual study activity</Link></>:<p className="text-muted">Choose a scenario to see its calculated effect. No activity will be saved.</p>}</Card></div></>;
}
